# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/apps.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/look.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/permissions.conf
exec-once = asusctl profile set Quiet
bind = $mainMod, F1, exec, asusctl profile set Quiet
bind = $mainMod, F2, exec, asusctl profile set Balanced
bind = $mainMod, F3, exec, asusctl profile set Performance
