# hyprpaper
# https://wiki.hypr.land/hypr-ecosystem/hyprpaper/
#
# Like hyprlock, hyprpaper is a separate program and still uses hyprlang.
#
# Paths must be absolute -- hyprpaper does not expand `~` here.

ipc = on
splash = false

preload = /home/kbauer/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
wallpaper = eDP-1,/home/kbauer/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
