###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$clipboard = cliphist
$fileManager = dolphin
$menu = wofi --show drun --prompt="App Launcher"
